name: ceenes_prototype
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  tmdb_api:
  flutter:
    sdk: flutter
  carousel_slider: ^2.3.1
  cupertino_icons: ^1.0.0
  flutter_tindercard: ^0.1.7
  sticky_headers: 
  smart_select: ^4.3.2
  firebase_core: "0.5.2"
  cloud_firestore: "^0.14.3"
  pinput: ^0.2.0
  chips_choice: ^2.0.1
  introduction_screen: ^1.0.9
  circular_reveal_animation: ^1.1.5
  expandable: ^4.1.4
  http:
  clipboard: ^0.1.2+8
  share: ^0.6.5+4
  auto_size_text: ^2.1.0
  url_launcher: ^5.7.10






dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/


